module.exports = {
  productList: [
    {
      name: 'Party Pineapple Hangover Inhibitor',
      id: 0,
      mainImage: '../images/ultima-electrolyte-powder.jpg',
      price: 24.99,
      flavor: 'Pineapple',
      description: '',
      meta: '47',
      sku: 'deez',
    },
    {
      name: 'Orange Hangover Inhibitor',
      id: 1,
      mainImage: '../images/ultima-electrolyte-powder.jpg',
      price: 24.99,
      flavor: 'Orange',
      description: 'Add product description here',
      meta: '47',
      sku: 'deez',
    },
    {
      name: 'Strawberry Lemonade Hangover Inhibitor',
      id: 2,
      mainImage: '../images/ultima-electrolyte-powder.jpg',
      price: 24.99,
      flavor: 'Strawberry Lemonade',
      description: 'Add product description here',
      meta: '47',
      sku: 'deez',
    },
    {
      name: 'Blasted Blue Raspberry Hangover Inhibitor',
      id: 3,
      mainImage: '../images/ultima-electrolyte-powder.jpg',
      price: 24.99,
      flavor: 'Blasted Blue Raspberry',
      description: 'Add product description here',
      meta: '47',
      sku: 'deez',
    },
    {
      name: 'Wasted Watermelon Hangover Inhibitor',
      id: 4,
      mainImage: '../images/ultima-electrolyte-powder.jpg',
      price: 24.99,
      flavor: 'Wasted Watermelon',
      description: 'Add product description here',
      meta: '47',
      sku: 'deez',
    },
    {
      name: 'Mango Hangover Inhibitor',
      id: 5,
      mainImage: '../images/ultima-electrolyte-powder.jpg',
      price: 24.99,
      flavor: 'Mango',
      description: 'Add product description here',
      meta: '47',
      sku: 'deez',
    },
  ],
}
